PARAM_BUTTONS_PARAMS =    {
    'UpscaleState':             False,
    'UpscaleMode':              0,
    'UpscaleModes':             ['GFPGAN', 'CF', 'GPEN256', 'GPEN512'],
    'UpscaleAmount':            [100, 100, 100, 100],
    'UpscaleMin':               0,
    'UpscaleMax':               100,
    'UpscaleInc':               5,                            
    'UpscaleUnit':              '%', 
    'UpscaleIcon':              './rope/media/gfpgan_logo.png',
    'UpscaleMessage':           '放大 - 放大人脸 [LB: on/off, RB: GFPGAN/Codeformer/GPEN256/GPEN512, MW: amount]',  
    
    'DiffState':                False,
    'DiffMode':                 0, 
    'DiffModes':                ['差异'], 
    'DiffAmount':               [4],
    'DiffMin':                  0,
    'DiffMax':                  100,
    'DiffInc':                  2,                                                  
    'DiffUnit':                 '%', 
    'DiffIcon':                 './rope/media/diff.png',
    'DiffMessage':              'DIFFERENCER - 基于像素差异在目标面和交换面之间混合。 [LB: on/off, MW: difference threshold]',
    
    'BorderState':                False,
    'BorderMode':                 0, 
    'BorderModes':                ['顶部遮罩', '两侧遮罩', '底部遮罩', '遮罩模糊'],  
    'BorderAmount':               [10, 10, 10, 10],
    'BorderMin':                  0,
    'BorderMax':                  64,
    'BorderInc':                  1,                                                 
    'BorderUnit':                 '%', 
    'BorderIcon':                 './rope/media/maskup.png',
    'BorderMessage':              'BORDER - 一个顶部、底部和侧面可调的矩形，用于混合交换面。 [RB: top/sides/bottom/blur, MW: amount]',   
    
    'MaskViewState':            False,
    'MaskViewMode':             0, 
    'MaskViewModes':            ['显示遮罩'],  
    'MaskViewAmount':           [5],
    'MaskViewMin':              0,
    'MaskViewMax':              50,
    'MaskViewInc':              0,                                                 
    'MaskViewUnit':             '', 
    'MaskViewIcon':             './rope/media/maskblur.png',
    'MaskViewMessage':          '显示遮罩 - 显示与面部并排的面部面具。有助于理解掩蔽行为和结果。[LB: on/off]', 

    'CLIPState':                False,
    'CLIPMode':                 0, 
    'CLIPModes':                ['文本遮罩'], 
    'CLIPAmount':               [50],
    'CLIPMin':                  0,
    'CLIPMax':                  100,
    'CLIPInc':                  1,                                                  
    'CLIPUnit':                 '%', 
    'CLIPIcon':                 './rope/media/CLIP.png',
    'CLIPMessage':              '文本遮罩 - 基于文本的封堵器。遮挡的对象在最终图像中可见（从遮罩遮挡）。[LB: on/off, MW: strength]',                              

    'OccluderState':            False,
    'OccluderMode':             0, 
    'OccluderModes':            ['自动遮罩'],  
    'OccluderAmount':           [0],
    'OccluderMin':              -100,
    'OccluderMax':              100,
    'OccluderInc':              1,                                                 
    'OccluderUnit':             '%', 
    'OccluderIcon':             './rope/media/occluder.png',
    'OccluderMessage':          '自动遮罩 - 面区域中的任何对象都会被遮挡。[LB: on/off, MW: additional size]', 
    
    'FaceParserState':          False,
    'FaceParserMode':           0, 
    'FaceParserModes':          ['嘴型遮罩', '背景'],  
    'FaceParserAmount':         [0, 0],
    'FaceParserMin':            -50,
    'FaceParserMax':            50,
    'FaceParserInc':            1,                                                 
    'FaceParserUnit':           '%', 
    'FaceParserIcon':           './rope/media/parse.png',
    'FaceParserMessage':        '基于特征执行遮挡。[LB:开/关，RB:嘴/除了脸以外的所有东西，MW:量（0为关，＜0为嘴内仅用于嘴模式）]',
    
    'BlurState':                False,
    'BlurMode':                 0, 
    'BlurModes':                ['遮罩模糊'],  
    'BlurAmount':               [5],
    'BlurMin':                  0,
    'BlurMax':                  100,
    'BlurInc':                  1,                                                 
    'BlurUnit':                 '%', 
    'BlurIcon':                 './rope/media/blur.png',
    'BlurMessage':              '遮罩模糊 - 模糊组合遮罩以软化边缘。未应用于初始掩码。[MW: amount]',
    
    'ThresholdState':           False,
    'ThresholdMode':            0, 
    'ThresholdModes':           ['人脸阈值'],  
    'ThresholdAmount':          [85],
    'ThresholdMin':             0,
    'ThresholdMax':             100,
    'ThresholdInc':             1,                                                 
    'ThresholdUnit':            '%', 
    'ThresholdIcon':            './rope/media/thresh.png',
    'ThresholdMessage':         '人脸阈值 - 用于确定“目标面”是否与帧中的面匹配的阈值。越低越严格。[LB: use amount/match all, MW: value]',
    
    'StrengthState':            False,
    'StrengthMode':             0, 
    'StrengthModes':            ['交换强度'],  
    'StrengthAmount':           [100],
    'StrengthMin':              25,
    'StrengthMax':              500,
    'StrengthInc':              25,                                                 
    'StrengthUnit':             '%', 
    'StrengthIcon':             './rope/media/strength.png',
    'StrengthMessage':          '交换强度 - 交换器模型的强度。这将执行每100%的额外迭代(100%=1, 200%=2, ... [MW: amount]',     

    'OrientationState':         False,
    'OrientationMode':          0, 
    'OrientationModes':         ['人脸方位'],  
    'OrientationAmount':        [0],
    'OrientationMin':           0,
    'OrientationMax':           270,
    'OrientationInc':           90,                                                 
    'OrientationUnit':          '%', 
    'OrientationIcon':          './rope/media/orient.png',
    'OrientationMessage':       '人脸方位 - 旋转人脸检测器可以更好地检测不同角度的人脸。[MW: angle]',          


    
    'RefDelState':         False,
    'RefDelMode':          0, 
    'RefDelModes':         ['垂直偏移', '水平偏移', '大小缩放'],  
    'RefDelAmount':        [0, 0, 0],
    'RefDelMin':           -100,
    'RefDelMax':           100,
    'RefDelInc':           1,                                                 
    'RefDelUnit':          '%', 
    'RefDelIcon':          './rope/media/construction.png',
    'RefDelMessage':       'REFERENCE DELTA - 修改参照点。启用遮罩预览以查看调整。[LB: on/off, RB: translate x/y, and scale, MW: amount]',      

    'TransformState':         False,
    'TransformMode':          0, 
    'TransformModes':         ['目标缩放'],  
    'TransformAmount':        [0],
    'TransformMin':           -20,
    'TransformMax':           20,
    'TransformInc':           1,                                                 
    'TransformUnit':          '%', 
    'TransformIcon':          './rope/media/scale.png',
    'TransformMessage':       '目标缩放 - 调整面的比例。与背景分析器一起使用可以混合到图像中。[LB: on/off, MW: amount]',       
    
    'ColorState':           False,
    'ColorMode':            0, 
    'ColorModes':           ['红', '绿', '蓝'],  
    'ColorAmount':           [0, 0, 0],
    'ColorMin':             -100,
    'ColorMax':             100,
    'ColorInc':             1,                                                 
    'ColorUnit':            'i', 
    'ColorIcon':            './rope/media/rgb.png',
    'ColorMessage':         'RGB ADJUSTMENT - 调整面的比例。与背景分析器一起使用可以混合到图像中。 [LB: on/off, RB: Red/Green/Blue, MW: amount]',       
    
    "CLIPText":                 '',

    'AutoColorState':   False,
    'AutoColorMode':    0,
    'AutoColorModes':   ['自動配色'],
    'AutoColorAmount':  [100],
    'AutoColorMin':     0,
    'AutoColorMax':     100,
    'AutoColorInc':     5,
    'AutoColorUnit':    '%',
    'AutoColorIcon':    './rope/media/rgb.png',
    'AutoColorMessage': 'AUTO COLOR MATCH - 自動將換臉膚色配合目標臉色調。[LB: on/off, MW: 混合強度 0-100%]',

    'FrameEnhanceState':    False,
    'FrameEnhanceMode':     0,
    'FrameEnhanceModes':    ['x2', 'x4'],
    'FrameEnhanceAmount':   [0, 0],
    'FrameEnhanceMin':      0,
    'FrameEnhanceMax':      0,
    'FrameEnhanceInc':      0,
    'FrameEnhanceUnit':     '',
    'FrameEnhanceIcon':     './rope/media/gfpgan_logo.png',
    'FrameEnhanceMessage':  '全幀增強 - 對整個畫面做超解析度，不換臉也可用。[LB: on/off, RB: x2/x4]',

    # 'ImgVid':                   'Video',
    }
    
PARAM_BUTTONS_CONSTANT = {   
    }
                
ACTIONS =   {
    'DockState':                False,
    'DockMode':                 0, 
    'DockModes':                [''],                         
    'DockIcon':                 './rope/media/dock.png',
    'DockMessage':              'DOCK/UNDOCK WINDOW - 取消锁定窗口-取消锁定窗口区域。无法重新停靠。', 
    'DockButton':               [],
    'DockIconHolder':           [],

    'ImgDockState':                False,
    'ImgDockMode':                 0, 
    'ImgDockModes':                [''],                         
    'ImgDockIcon':                 './rope/media/dock.png',
    'ImgDockMessage':              'DOCK/UNDOCK WINDOW - 图片取消锁定窗口-取消锁定窗口区域。无法重新停靠。', 
    'ImgDockButton':               [],
    'ImgDockIconHolder':           [],    
    
    'SaveImageState':                False,
    'SaveImageMode':                 0, 
    'SaveImageModes':                [''],                         
    'SaveImageIcon':                 './rope/media/save_disk.png',
    'SaveImageMessage':              'SAVE IMAGE - 保存图像到输出目录', 
    'SaveImageButton':               [],
    'SaveImageIconHolder':           [],
    
    'AutoSwapState':           False,
    'AutoSwapMode':            0, 
    'AutoSwapModes':           ['Auto'],                         
    'AutoSwapIcon':            './rope/media/construction.png',
    'AutoSwapMessage':         'AUTO SWAP - 自动将图像中的第一个人交换到选定的源面[LB: Turn on/off]', 
    'AutoSwapButton':          [],
    'AutoSwapIconHolder':      [],    
    
    'PlayState':                False,
    'PlayMode':                 0, 
    'PlayModes':                [''],                         
    'PlayIcon':                 './rope/media/play.png',
    'PlayMessage':              '播放 - 播放视频，再次点击停止播放', 
    'PlayButton':               [],
    'PlayIconHolder':           [],
    
    'RecordState':              False,
    'RecordMode':               0, 
    'RecordModes':              [''],                         
    'RecordIcon':               './rope/media/rec.png',
    'RecordMessage':            '录制 - 按下播放按钮进行录制。按RECORD，然后按PLAY进行录制。再次按“播放”可停止录制。', 
    'RecordButton':             [],
    'RecordIconHolder':         [],  

    'AddMarkerState':           False,
    'AddMarkerMode':            0, 
    'AddMarkerModes':           [''],                         
    'AddMarkerIcon':            './rope/media/add.png',
    'AddMarkerMessage':         '添加标记 - 获取当前帧的参数标记。标记会复制所有参数设置并将其应用于未来的所有帧，或者直到遇到另一个标记为止。',
    'AddMarkerButton':          [],
    'AddMarkerIconHolder':      [],  

    'RemoveMarkerState':        False,
    'RemoveMarkerMode':         0, 
    'RemoveMarkerModes':        [''],                         
    'RemoveMarkerIcon':         './rope/media/remove.png',
    'RemoveMarkerMessage':      '移除标记 - 从当前帧中删除参数标记。', 
    'RemoveMarkerButton':       [],
    'RemoveMarkerIconHolder':   [],  

    'PrevMarkerState':          False,
    'PrevMarkerMode':           0, 
    'PrevMarkerModes':          [''],                         
    'PrevMarkerIcon':           './rope/media/prev.png',
    'PrevMarkerMessage':        '上一个标记 - 移动到上一个标记。', 
    'PrevMarkerButton':         [],
    'PrevMarkerIconHolder':     [],         

    'NextMarkerState':          False,
    'NextMarkerMode':           0, 
    'NextMarkerModes':          [''],                         
    'NextMarkerIcon':           './rope/media/next.png',
    'NextMarkerMessage':        '下一个标记 - 移动到下一个标记。', 
    'NextMarkerButton':         [],
    'NextMarkerIconHolder':     [],  

    'ToggleStopState':          False,
    'ToggleStopMode':           0, 
    'ToggleStopModes':          [''],                         
    'ToggleStopIcon':           './rope/media/STOP.png',
    'ToggleStopMessage':        '停止标记-设置一个将停止视频播放/录制的帧。', 
    'ToggleStopButton':         [],
    'ToggleStopIconHolder':     [],                  
    

    'FindFacesState':           False,
    'FindFacesMode':            0, 
    'FindFacesModes':           ['查找人脸'],                         
    'FindFacesIcon':            './rope/media/tarface.png',
    'FindFacesMessage':         '查找人脸 - 查找当前帧中的所有脸。',     

    'ClearFacesState':          False,
    'ClearFacesMode':           0, 
    'ClearFacesModes':          ['移除人脸'],                         
    'ClearFacesIcon':           './rope/media/tarfacedel.png',
    'ClearFacesMessage':        '移除人脸 - 清除所有找到的脸',   

    'SwapFacesState':           False,
    'SwapFacesMode':            0, 
    'SwapFacesModes':           ['交换人脸'],                         
    'SwapFacesIcon':            './rope/media/swap.png',
    'SwapFacesMessage':         '交换人脸 - 交换指定的源面和目标人脸', 
    'SwapFacesButton':          [],
    'SwapFacesIconHolder':      [],
    
 
    'LoadSFacesState':           False,
    'LoadSFacesMode':            0, 
    'LoadSFacesModes':           [''],                         
    'LoadSFacesIcon':            './rope/media/save.png',
    'LoadSFacesMessage':         '加载源人脸 - 从文件夹加载源面。请确保文件夹中只包含<good>图像。', 
    'LoadSFacesButton':          [],
    'LoadSFacesIconHolder':      [],

    'DelEmbedState':           False,
    'DelEmbedMode':            0, 
    'DelEmbedModes':           ['删除关联'],                         
    'DelEmbedIcon':            './rope/media/delemb.png',
    'DelEmbedMessage':         '删除关联 - 删除当前选定的对应关系', 
    'DelEmbedButton':          [],
    'DelEmbedIconHolder':      [],

    'LoadTVideosState':           False,
    'LoadTVideosMode':            0, 
    'LoadTVideosModes':           [''],                         
    'LoadTVideosIcon':            './rope/media/save.png',
    'LoadTVideosMessage':         '加载目标视频/图片 - 加载目标目录', 
    'LoadTVideosButton':          [],
    'LoadTVideosIconHolder':      [],

    'ImgVidState':           False,
    'ImgVidMode':            0, 
    'ImgVidModes':           ['视频', '图像'],                         
    'ImgVidIcon':            './rope/media/imgvid.png',
    'ImgVidMessage':         '视频/图像 - 在“图像”和“视频”文件夹视图之间切换', 
    'ImgVidButton':          [],
    'ImgVidIconHolder':      [],

    'BatchRecordState':         False,
    'BatchRecordMode':          0,
    'BatchRecordModes':         ['批量錄製'],
    'BatchRecordIcon':          './rope/media/rec.png',
    'BatchRecordMessage':       '批量錄製 - 對目錄內所有影片依序錄製輸出',
    'BatchRecordButton':        [],
    'BatchRecordIconHolder':    [],

    'StopBatchState':           False,
    'StopBatchMode':            0,
    'StopBatchModes':           ['停止批量'],
    'StopBatchIcon':            './rope/media/STOP.png',
    'StopBatchMessage':         '停止批量 - 停止目前批量錄製排程',
    'StopBatchButton':          [],
    'StopBatchIconHolder':      [],

    'HoldFaceState':           False,
    'HoldFaceMode':            0, 
    'HoldFaceModes':           ['HoldFace'],                         
    'HoldFaceIcon':            './rope/media/imgvid.png',
    'HoldFaceMessage':         'IMAGE/VIDEO - 在图像和视频文件夹视图之间切换。', 
    'HoldFaceButton':          [],
    'HoldFaceIconHolder':      [],     
    
    'StartRopeState':           False,
    'StartRopeMode':            0, 
    'StartRopeModes':           ['开始ROPE'],                         
    'StartRopeIcon':            './rope/media/save.png',
    'StartRopeMessage':         '开始ROPE - 加载所有文件夹并初始化模型', 
    'StartRopeButton':          [],
    'StartRopeIconHolder':      [],      
    
    'OutputFolderState':           False,
    'OutputFolderMode':            0, 
    'OutputFolderModes':           [''],                         
    'OutputFolderIcon':            './rope/media/save.png',
    'OutputFolderMessage':         '输出目录 - 为图像和视频输出选择文件夹', 
    'OutputFolderButton':          [],
    'OutputFolderIconHolder':      [],  
    
    'ThreadsState':           False,
    'ThreadsMode':            0, 
    'ThreadsModes':           [''],                         
    'ThreadsIcon':            './rope/media/threads.png',
    'ThreadsMessage':         '线程数 - 设置执行线程数。按下PLAY后，减少线程数不会释放内存.[MW: set number of threads]', 
    'ThreadsButton':          [],
    'ThreadsIconHolder':      [],  

    'VideoQualityState':           False,
    'VideoQualityMode':            0, 
    'VideoQualityModes':           [''],                         
    'VideoQualityIcon':            './rope/media/tarface.png',
    'VideoQualityMessage':         '视频质量 - 录制视频的编码质量。0是最好的，50是wrost，18大部分是无损的。文件大小随着质量编号的降低而增加',
    'VideoQualityButton':          [],
    'VideoQualityIconHolder':      [],  
    
    'PerfTestState':           False,
    'PerfTestMode':            0, 
    'PerfTestModes':           ['性能测试'],                         
    'PerfTestIcon':            './rope/media/test.png',
    'PerfTestMessage':         'PERFORMANCE DATA - 在控制台中显示关键Rope功能的计时数据。[LB: on/off]', 
    'PerfTestButton':          [],
    'PerfTestIconHolder':      [], 

    'ClearmemState':           False,
    'ClearmemMode':            0, 
    'ClearmemModes':           ['释放'],                         
    'ClearmemIcon':            './rope/media/clear_mem.png',
    'ClearmemMessage':         'CLEAR VRAM-清除VRAM中的所有models [LB: Clear]', 
    'ClearmemButton':          [],
    'ClearmemIconHolder':      [],      

    # 'State':           False,
    # 'Mode':            0, 
    # 'Modes':           ['Videos', 'Images'],                         
    # 'Icon':            './rope/media/imgvid.png',
    # 'Message':         'IMAGE/VIDEO - Toggle between Image and Video folder view.', 
    # 'Button':          [],
    # 'IconHolder':      [],      
    
    
     }   